In [1]:
import torch

print(torch.__version__)
#importing pytorch and checking whether it is correctly connected. One should also check out the cuda related article by pytorch, so that cuda was installed correctly

2.6.0+cu126


In [2]:
scalar = torch.tensor(7)
scalar
#scalar is a 0d tensor

tensor(7)

In [3]:
scalar.ndim
#checking number of dimensions. Predictably, 0 for scalar

0

In [4]:
scalar.item()
#returns the number stored in scalar

7

In [5]:
vector = torch.tensor([7, 7])
vector
#creating a vector (1d tensor)

tensor([7, 7])

In [14]:
vector.shape
#returns vector's shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX
#creating a matrix (2d tensor)

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.shape
#returns matrix's shape

torch.Size([2, 2])

In [10]:
TENSOR = torch.tensor([[1,2,3],
                       [3,6,9],
                       [2,4,5]])
TENSOR
#creating tensor

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [11]:
TENSOR.ndim
#checking number of dimensions. It is easy countable by brackets on one side of the argument

2

In [12]:
TENSOR.shape
#checking tensor's shape

torch.Size([3, 3])

In [13]:
random_tensor = torch.randn(size=(3, 4))
random_tensor, random_tensor.dtype
#creating a random tensor. Basically ML starts from random tensor and finds the best values.

(tensor([[ 1.6562, -1.2672,  3.0527,  0.6731],
         [ 0.6953, -1.4153, -0.3018, -0.7075],
         [ 0.5909,  1.2305, -2.4895,  0.7293]]),
 torch.float32)

In [14]:
random_image_tensor = torch.randn(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.dtype
#example of tensor that can represent an image. Size of image 224x224, 3 color channels

(torch.Size([224, 224, 3]), torch.float32)

In [15]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype
#creating a tensor filled with zeros only

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [16]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype
#creating a tensor filled with ones only

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [18]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten
#creating a tensor with the numbers ranged 0-9

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros
#zeros_like() is used to create a tensor with the same shape as the one in "input" parameter, but filled with zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device
#creating a tensor with some specified parameters. To perform operations between tensors, they should have the same dtype, be stored on the same device and have appropriate shapes.

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device
#specifiyng dtype for the tensor. The more precise the dtype is, the more effective the model will be able to perform (because it could represent more details in numbers)

(torch.Size([3]), torch.float16, device(type='cpu'))

In [28]:
some_tensor = torch.randn(size=(3, 4))
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")
#printing out some essential information about the tensor.

tensor([[-0.5791, -0.7918,  1.4436, -0.0924],
        [ 0.5974,  0.0301,  0.8456, -1.4838],
        [-0.6423,  0.6017, -0.9330,  0.1618]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [33]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
tensor
#tensor can be modified by these mathematical operations. They are calculated element-wise. The changes aren't saved for the tensor as long as it hasn't been reassigned

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])


tensor([1, 2, 3])

In [27]:
tensor -= 10
tensor
#subtraction with reassignment.

tensor([1, 2, 3])

In [26]:
tensor += 10
tensor
#adding with reassignment.

tensor([11, 12, 13])

In [25]:
print(torch.multiply(tensor, 10))
tensor
#multiplication using built-in function

tensor([10, 20, 30])


tensor([1, 2, 3])

In [24]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
#element-wise multiplication

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [23]:
tensor = torch.tensor([1, 2, 3])
tensor.shape
#creating new tensor

torch.Size([3])

In [28]:
print(tensor * tensor)
print(torch.matmul(tensor, tensor))
tensor @ tensor
#matrix multiplication. One can perform it using torch.matmul() or sign "@"

tensor([1, 4, 9])
tensor(14)


tensor(14)