In [2]:
import torch
print(torch.__version__)

2.6.0+cu126


In [8]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [13]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
vector.shape

torch.Size([2])

In [15]:
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
TENSOR = torch.tensor([[1,2,3],
                       [3,6,9],
                       [2,4,5]])
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
TENSOR.ndim

2

In [19]:
TENSOR.shape

torch.Size([3, 3])