In [57]:
import torch

print(torch.__version__)
#importing pytorch and checking whether it is correctly connected. One should also check out the cuda related article by pytorch, so that cuda was installed correctly

2.6.0+cu126


In [58]:
scalar = torch.tensor(7)
scalar
#scalar is a 0d tensor

tensor(7)

In [59]:
scalar.ndim
#checking number of dimensions. Predictably, 0 for scalar

0

In [60]:
scalar.item()
#returns the number stored in scalar

7

In [61]:
vector = torch.tensor([7, 7])
vector
#creating a vector (1d tensor)

tensor([7, 7])

In [62]:
vector.shape
#returns vector's shape

torch.Size([2])

In [63]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX
#creating a matrix (2d tensor)

tensor([[ 7,  8],
        [ 9, 10]])

In [64]:
MATRIX.shape
#returns matrix's shape

torch.Size([2, 2])

In [65]:
TENSOR = torch.tensor([[1,2,3],
                       [3,6,9],
                       [2,4,5]])
TENSOR
#creating tensor

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [66]:
TENSOR.ndim
#checking number of dimensions. It is easy countable by brackets on one side of the argument

2

In [67]:
TENSOR.shape
#checking tensor's shape

torch.Size([3, 3])

In [68]:
random_tensor = torch.randn(size=(3, 4))
random_tensor, random_tensor.dtype
#creating a random tensor. Basically ML starts from random tensor and finds the best values.

(tensor([[-0.4849,  0.4445, -0.2345, -0.0717],
         [-1.3590,  0.4315, -0.5487,  2.0684],
         [-0.4929,  0.6962, -2.6744, -0.2813]]),
 torch.float32)

In [69]:
random_image_tensor = torch.randn(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.dtype
#example of tensor that can represent an image. Size of image 224x224, 3 color channels

(torch.Size([224, 224, 3]), torch.float32)

In [70]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype
#creating a tensor filled with zeros only

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [71]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype
#creating a tensor filled with ones only

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [72]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten
#creating a tensor with the numbers ranged 0-9

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros
#zeros_like() is used to create a tensor with the same shape as the one in "input" parameter, but filled with zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device
#creating a tensor with some specified parameters. To perform operations between tensors, they should have the same dtype, be stored on the same device and have appropriate shapes.

(torch.Size([3]), torch.float32, device(type='cpu'))

In [75]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device
#specifiyng dtype for the tensor. The more precise the dtype is, the more effective the model will be able to perform (because it could represent more details in numbers)

(torch.Size([3]), torch.float16, device(type='cpu'))

In [76]:
some_tensor = torch.randn(size=(3, 4))
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")
#printing out some essential information about the tensor.

tensor([[ 0.5312, -0.8386, -0.8271,  0.0073],
        [ 0.7645, -1.1130,  0.8566, -0.7834],
        [-0.3389, -1.2434,  0.8135,  0.2553]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [77]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
tensor
#tensor can be modified by these mathematical operations. They are calculated element-wise. The changes aren't saved for the tensor as long as it hasn't been reassigned

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])


tensor([1, 2, 3])

In [78]:
tensor -= 10
tensor
#subtraction with reassignment.

tensor([-9, -8, -7])

In [79]:
tensor += 10
tensor
#adding with reassignment.

tensor([1, 2, 3])

In [80]:
print(torch.multiply(tensor, 10))
tensor
#multiplication using built-in function

tensor([10, 20, 30])


tensor([1, 2, 3])

In [81]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
#element-wise multiplication

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [82]:
tensor = torch.tensor([1, 2, 3])
tensor.shape
#creating new tensor

torch.Size([3])

In [83]:
print(tensor * tensor)
print(torch.matmul(tensor, tensor))
tensor @ tensor
#matrix multiplication. One can perform it using torch.matmul() or sign "@"

tensor([1, 4, 9])
tensor(14)


tensor(14)

In [84]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [30]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [31]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [32]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [33]:
torch.mm(tensor_A, tensor_B.T) #contraction from matmul
#http://matrixmultiplication.xyz/

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [37]:
torch.manual_seed(42) #setting a manual seed is crucial to get completely random values

linear = torch.nn.Linear(in_features=2, #shape of input
                         out_features=6) #shape of output
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [38]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3, #changing input shape
                         out_features=6)
x = tensor_A
output = linear(x.T) #using torch.transpose() to adjust the tensor's shape to the appropriate one
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


In [39]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") #would return an error, because float type should be processed
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [41]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x) #alternative approach to gather the information above

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [42]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

print(f"Index where max value occurs: {tensor.argmax()}") #returns the index of the maximal element
print(f"Index where min value occurs: {tensor.argmin()}") #returns the index of the minimal element

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [43]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [44]:
tensor_float16 = tensor.type(torch.float16) #changing the dtype to float16
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [45]:
tensor_int8 = tensor.type(torch.int8) #changing the dtype to int8
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [46]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [47]:
x_reshaped = x.reshape(1, 7) #changing the shape of the tensor
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [48]:
z = x.view(1, 7) #creating a view of the tensor
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [49]:
z[:, 0] = 5 #when view is edited, the changes are also applied for the original tensor
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [54]:
x_stacked = torch.stack([x, x, x, x], dim=0) #stacking tensors on each other
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [55]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze() #squeezing means deleting the dimensions with number 1
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [56]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0) #adding a dimension to the tensor (opposite of squeezing). dim specifies the dimension to add
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [57]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1) #changing the order of dimensions

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
