In [2]:
import torch
from sympy.codegen.ast import float16

print(torch.__version__)

2.6.0+cu126


In [8]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [13]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
vector.shape

torch.Size([2])

In [15]:
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
TENSOR = torch.tensor([[1,2,3],
                       [3,6,9],
                       [2,4,5]])
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
TENSOR.ndim

2

In [19]:
TENSOR.shape

torch.Size([3, 3])

In [20]:
random_tensor = torch.randn(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[-2.2745,  0.4300, -0.2481, -0.3817],
         [ 0.3089, -1.0004,  0.3204,  0.4827],
         [-0.5075, -0.1781,  1.1122,  0.8649]]),
 torch.float32)

In [21]:
random_image_tensor = torch.randn(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.dtype

(torch.Size([224, 224, 3]), torch.float32)

In [22]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [23]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [24]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [27]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device

(torch.Size([3]), torch.float16, device(type='cpu'))

In [28]:
some_tensor = torch.randn(size=(3, 4))
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[-0.5791, -0.7918,  1.4436, -0.0924],
        [ 0.5974,  0.0301,  0.8456, -1.4838],
        [-0.6423,  0.6017, -0.9330,  0.1618]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
